### ISSUE TITLE
可以利用 Python 特性简化代码

### ISSUE THREAD

**Issue by asukaminato0721** [drb-ecust/15-puzzle-#1]
https://github.com/drb-ecust/15-puzzle-/blob/f81e6eb3c749c126e6d6610c8da3571d8df9b156/github-15puzzle/slide_puzzle.py#L121

```py
high_surf = pygame.image.load(f"images_high/high_0{i}.jpg")
```

f-str

---

https://github.com/drb-ecust/15-puzzle-/blob/f81e6eb3c749c126e6d6610c8da3571d8df9b156/github-15puzzle/slide_puzzle.py#L144

```py
TIMES_SURF, TIMES_RECT = makeText(f"次数：{times}", (255, 0, 0), 629, 64, 25) 
```

---

以及可以适当用 dict 减少 if elif

```py
if a==1:
    f()
elif a==2:
    g()
elif a==3:
    h()
```

可以写成

```py
{1: f, 2: g, 3: h}[a]()
```

**Comment by Tiandooo** [comment]
谢谢大佬的建议，这是我大一时候的代码，刚刚才看到issue😂，非常感谢hhh
